from PyQt4 import QtCore, QtGui

class Ui_smartsyncdlg(object):
    
    def setupUi(self, smartsyncdlg):
        
        smartsyncdlg.setObjectName("smartsyncdlg")
        smartsyncdlg.resize(1000, 450)
        smartsyncdlg.setMinimumSize(QtCore.QSize(1000, 450))
        smartsyncdlg.setWindowIcon(QtGui.QIcon("data/reload_32.png"))
        smartsyncdlg.setDockOptions(QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(smartsyncdlg)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.mainTab = QtGui.QWidget()
        self.mainTab.setGeometry(QtCore.QRect(0, 0, 894, 348))
        self.mainTab.setObjectName("mainTab")
        self.gridLayout = QtGui.QGridLayout(self.mainTab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftLabel = QtGui.QLabel(self.mainTab)
        self.leftLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.leftLabel.setObjectName("leftLabel")
        self.verticalLayout.addWidget(self.leftLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.leftComboBox = QtGui.QComboBox(self.mainTab)
        self.leftComboBox.setEditable(True)
        self.leftComboBox.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.leftComboBox.setObjectName("leftComboBox")
        self.horizontalLayout.addWidget(self.leftComboBox)
        
        self.leftOpenButton = QtGui.QPushButton(self.mainTab)
        self.leftOpenButton.setMaximumSize(QtCore.QSize(22, 22))
        self.leftOpenButton.setObjectName("leftOpenButton")
        self.horizontalLayout.addWidget(self.leftOpenButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        
        self.leftTreeWidget = QtGui.QTreeWidget(self.mainTab)
        self.leftTreeWidget.setObjectName("leftTreeWidget")
        self.leftTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.leftTreeWidget.setAnimated(True)
        self.verticalLayout.addWidget(self.leftTreeWidget)
        
        self.leftBottomLabel = QtGui.QLabel(self.mainTab)
        self.leftBottomLabel.setFrameShape(QtGui.QFrame.Panel)
        self.leftBottomLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.leftBottomLabel.setObjectName("leftBottomLabel")
        self.verticalLayout.addWidget(self.leftBottomLabel)
        
        self.horizontalLayout_3.addLayout(self.verticalLayout)        
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        spacerItem = QtGui.QSpacerItem(20, 68, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        
        self.l2rPushButton = QtGui.QPushButton(self.mainTab)
        self.l2rPushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.l2rPushButton.setObjectName("l2rPushButton")
        self.verticalLayout_2.addWidget(self.l2rPushButton)
        
        self.eqPushButton = QtGui.QPushButton(self.mainTab)
        self.eqPushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.eqPushButton.setObjectName("eqPushButton")
        self.verticalLayout_2.addWidget(self.eqPushButton)
        
        self.r2lPushButton = QtGui.QPushButton(self.mainTab)
        self.r2lPushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.r2lPushButton.setObjectName("r2lPushButton")
        self.verticalLayout_2.addWidget(self.r2lPushButton)
        
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        self.rightLabel = QtGui.QLabel(self.mainTab)
        self.rightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rightLabel.setObjectName("rightLabel")
        self.verticalLayout_3.addWidget(self.rightLabel)
        
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.rightComboBox = QtGui.QComboBox(self.mainTab)
        self.rightComboBox.setEditable(True)
        self.rightComboBox.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.rightComboBox.setObjectName("rightComboBox")
        self.horizontalLayout_2.addWidget(self.rightComboBox)
        
        self.rightOpenButton = QtGui.QPushButton(self.mainTab)
        self.rightOpenButton.setMaximumSize(QtCore.QSize(22, 22))
        self.rightOpenButton.setObjectName("rightOpenButton")
        self.horizontalLayout_2.addWidget(self.rightOpenButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        
        self.rightTreeWidget = QtGui.QTreeWidget(self.mainTab)
        self.rightTreeWidget.setObjectName("rightTreeWidget")
        self.rightTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.rightTreeWidget.setAnimated(True)
        self.verticalLayout_3.addWidget(self.rightTreeWidget)
        
        self.rightBottomLabel = QtGui.QLabel(self.mainTab)
        self.rightBottomLabel.setFrameShape(QtGui.QFrame.Panel)
        self.rightBottomLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.rightBottomLabel.setObjectName("rightBottomLabel")
        self.verticalLayout_3.addWidget(self.rightBottomLabel)
        
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        
        self.toolBox.addItem(self.mainTab, "")
        self.optionsTab = QtGui.QWidget()
        self.optionsTab.setGeometry(QtCore.QRect(0, 0, 894, 348))
        self.optionsTab.setObjectName("optionsTab")
        self.gridLayout_99 = QtGui.QGridLayout(self.optionsTab)
        self.gridLayout_99.setObjectName("gridLayout_99")
        self.optionsGroupBox = QtGui.QGroupBox(self.optionsTab)
        
        self.optionsGroupBox.setObjectName("optionsGroupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.optionsGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        self.recursiveCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.recursiveCheckBox.setCheckable(True)
        self.recursiveCheckBox.setChecked(True)
        self.recursiveCheckBox.setObjectName("recursiveCheckBox")
        self.verticalLayout_4.addWidget(self.recursiveCheckBox)
        
        self.backupCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.backupCheckBox.setChecked(False)
        self.backupCheckBox.setObjectName("backupCheckBox")
        self.verticalLayout_4.addWidget(self.backupCheckBox)
        
        self.hiddenCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.hiddenCheckBox.setChecked(True)
        self.hiddenCheckBox.setObjectName("hiddenCheckBox")
        self.verticalLayout_4.addWidget(self.hiddenCheckBox)
        
        self.contentCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.contentCheckBox.setObjectName("contentCheckBox")
        self.verticalLayout_4.addWidget(self.contentCheckBox)
        
        self.ownershipCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.ownershipCheckBox.setChecked(True)
        self.ownershipCheckBox.setObjectName("ownershipCheckBox")
        self.verticalLayout_4.addWidget(self.ownershipCheckBox)
        
        self.permissionsCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.permissionsCheckBox.setChecked(True)
        self.permissionsCheckBox.setObjectName("permissionsCheckBox")
        self.verticalLayout_4.addWidget(self.permissionsCheckBox)
        
        self.timestampsCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.timestampsCheckBox.setChecked(True)
        self.timestampsCheckBox.setObjectName("timestampsCheckBox")
        self.verticalLayout_4.addWidget(self.timestampsCheckBox)
        
        self.unidirCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        #self.unidirCheckBox.setChecked(True)
        self.unidirCheckBox.setObjectName("unidirCheckBox")
        self.verticalLayout_4.addWidget(self.unidirCheckBox)
        
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.l2rRadioButton = QtGui.QRadioButton(self.optionsGroupBox)
        self.l2rRadioButton.setEnabled(False)
        self.l2rRadioButton.setChecked(True)
        self.l2rRadioButton.setObjectName("l2rRadioButton")
        self.verticalLayout_5.addWidget(self.l2rRadioButton)
        
        self.r2lRadioButton = QtGui.QRadioButton(self.optionsGroupBox)
        self.r2lRadioButton.setEnabled(False)
        self.r2lRadioButton.setObjectName("r2lRadioButton")
        self.verticalLayout_5.addWidget(self.r2lRadioButton)
        
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_99.addWidget(self.optionsGroupBox,0,0,1,1)
        
        self.excludeGroupBox = QtGui.QGroupBox(self.optionsTab)
        self.excludeGroupBox.setObjectName("excludeGroupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.excludeGroupBox)
        
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.excludeLineEdit = QtGui.QLineEdit(self.excludeGroupBox)
        #self.excludeComboBox.setEditable(True)
        #self.excludeComboBox.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.excludeLineEdit.setObjectName("excludeLineEdit")
        self.horizontalLayout_5.addWidget(self.excludeLineEdit)
        
        self.excludeOpenButton = QtGui.QPushButton(self.excludeGroupBox)
        self.excludeOpenButton.setMaximumSize(QtCore.QSize(22, 22))
        self.excludeOpenButton.setObjectName("excludeOpenButton")
        self.horizontalLayout_5.addWidget(self.excludeOpenButton)        
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        
        self.excludeListWidget = QtGui.QListWidget(self.excludeGroupBox)
        self.excludeListWidget.setObjectName("excludeListWidget")
        self.verticalLayout_8.addWidget(self.excludeListWidget)
        
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        
        self.addPushButton = QtGui.QPushButton(self.excludeGroupBox)
        self.addPushButton.setObjectName("addPushButton")
        #self.addPushButton.setEnabled(False)
        self.verticalLayout_7.addWidget(self.addPushButton)
        
        self.removePushButton = QtGui.QPushButton(self.excludeGroupBox)
        self.removePushButton.setObjectName("removePushButton")
        #self.removePushButton.setEnabled(False)
        self.verticalLayout_7.addWidget(self.removePushButton)
        
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout_99.addWidget(self.excludeGroupBox,0,1,1,1)
        self.toolBox.addItem(self.optionsTab, "")
        self.gridLayout_4.addWidget(self.toolBox, 0, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        
        self.comparePushButton = QtGui.QPushButton(self.centralwidget)
        self.comparePushButton.setMaximumSize(QtCore.QSize(80, 27))
        self.comparePushButton.setObjectName("comparePushButton")
        self.verticalLayout_9.addWidget(self.comparePushButton)
        
        self.syncPushButton = QtGui.QPushButton(self.centralwidget)
        self.syncPushButton.setMaximumSize(QtCore.QSize(80, 27))
        self.syncPushButton.setObjectName("syncPushButton")
        self.verticalLayout_9.addWidget(self.syncPushButton)
        
        spacerItem4 = QtGui.QSpacerItem(20, 178, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        
        #self.profilesPushButton = QtGui.QPushButton(self.centralwidget)
        #self.profilesPushButton.setMaximumSize(QtCore.QSize(80, 27))
        #self.profilesPushButton.setObjectName("profilesPushButton")
        #self.verticalLayout_9.addWidget(self.profilesPushButton)
        
        #self.helpPushButton = QtGui.QPushButton(self.centralwidget)
        #self.helpPushButton.setMaximumSize(QtCore.QSize(80, 27))
        #self.helpPushButton.setObjectName("helpPushButton")
        #self.verticalLayout_9.addWidget(self.helpPushButton)
        
        self.closePushButton = QtGui.QPushButton(self.centralwidget)
        self.closePushButton.setMaximumSize(QtCore.QSize(80, 27))
        self.closePushButton.setObjectName("closePushButton")
        self.verticalLayout_9.addWidget(self.closePushButton)
        
        self.gridLayout_4.addLayout(self.verticalLayout_9, 0, 1, 1, 1)
        smartsyncdlg.setCentralWidget(self.centralwidget)
        
        self.statusbar = QtGui.QStatusBar(smartsyncdlg)
        self.statusbar.setObjectName("statusbar")
        smartsyncdlg.setStatusBar(self.statusbar)
        
        self.leftLabel.setBuddy(self.leftComboBox)
        self.rightLabel.setBuddy(self.rightComboBox)

        self.retranslateUi(smartsyncdlg)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.closePushButton, QtCore.SIGNAL("clicked()"), smartsyncdlg.close)
        QtCore.QObject.connect(self.leftTreeWidget, QtCore.SIGNAL("clicked(QModelIndex)"), self.rightTreeWidget.clearSelection)
        QtCore.QObject.connect(self.rightTreeWidget, QtCore.SIGNAL("clicked(QModelIndex)"), self.leftTreeWidget.clearSelection)
        QtCore.QMetaObject.connectSlotsByName(smartsyncdlg)
        smartsyncdlg.setTabOrder(self.leftComboBox, self.leftOpenButton)
        smartsyncdlg.setTabOrder(self.leftOpenButton, self.rightComboBox)
        smartsyncdlg.setTabOrder(self.rightComboBox, self.rightOpenButton)
        smartsyncdlg.setTabOrder(self.rightOpenButton, self.comparePushButton)
        smartsyncdlg.setTabOrder(self.comparePushButton, self.l2rPushButton)
        smartsyncdlg.setTabOrder(self.l2rPushButton, self.eqPushButton)
        smartsyncdlg.setTabOrder(self.eqPushButton, self.r2lPushButton)
        smartsyncdlg.setTabOrder(self.r2lPushButton, self.syncPushButton)
        smartsyncdlg.setTabOrder(self.syncPushButton, self.recursiveCheckBox)
        smartsyncdlg.setTabOrder(self.recursiveCheckBox, self.backupCheckBox)
        smartsyncdlg.setTabOrder(self.backupCheckBox, self.hiddenCheckBox)
        smartsyncdlg.setTabOrder(self.hiddenCheckBox, self.contentCheckBox)
        smartsyncdlg.setTabOrder(self.contentCheckBox, self.ownershipCheckBox)
        smartsyncdlg.setTabOrder(self.ownershipCheckBox, self.permissionsCheckBox)
        smartsyncdlg.setTabOrder(self.permissionsCheckBox, self.timestampsCheckBox)
        smartsyncdlg.setTabOrder(self.timestampsCheckBox, self.unidirCheckBox)
        smartsyncdlg.setTabOrder(self.unidirCheckBox, self.l2rRadioButton)
        smartsyncdlg.setTabOrder(self.l2rRadioButton, self.r2lRadioButton)
        smartsyncdlg.setTabOrder(self.r2lRadioButton, self.excludeLineEdit)
        smartsyncdlg.setTabOrder(self.excludeLineEdit, self.excludeOpenButton)
        smartsyncdlg.setTabOrder(self.excludeOpenButton, self.addPushButton)
        smartsyncdlg.setTabOrder(self.addPushButton, self.removePushButton)
        smartsyncdlg.setTabOrder(self.removePushButton, self.excludeListWidget)
        smartsyncdlg.setTabOrder(self.excludeListWidget, self.closePushButton)
        #smartsyncdlg.setTabOrder(self.excludeListWidget, self.profilesPushButton)
        #smartsyncdlg.setTabOrder(self.profilesPushButton, self.helpPushButton)
        #smartsyncdlg.setTabOrder(self.helpPushButton, self.closePushButton)

    def retranslateUi(self, smartsyncdlg):
        smartsyncdlg.setWindowTitle(QtGui.QApplication.translate("smartsyncdlg", "Smart Synchroniser", None, QtGui.QApplication.UnicodeUTF8))
        self.leftLabel.setText(QtGui.QApplication.translate("smartsyncdlg", "&Left directory", None, QtGui.QApplication.UnicodeUTF8))
        self.leftOpenButton.setText(QtGui.QApplication.translate("smartsyncdlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.leftTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("smartsyncdlg", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.leftTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("smartsyncdlg", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.leftTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("smartsyncdlg", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.leftBottomLabel.setText(QtGui.QApplication.translate("smartsyncdlg", "", None, QtGui.QApplication.UnicodeUTF8))
        self.l2rPushButton.setText(QtGui.QApplication.translate("smartsyncdlg", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.eqPushButton.setText(QtGui.QApplication.translate("smartsyncdlg", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.r2lPushButton.setText(QtGui.QApplication.translate("smartsyncdlg", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.rightLabel.setText(QtGui.QApplication.translate("smartsyncdlg", "&Right directory", None, QtGui.QApplication.UnicodeUTF8))
        self.rightOpenButton.setText(QtGui.QApplication.translate("smartsyncdlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.rightTreeWidget.setSortingEnabled(True)
        self.leftTreeWidget.setSortingEnabled(True)
        self.rightTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("smartsyncdlg", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.rightTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("smartsyncdlg", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.rightTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("smartsyncdlg", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.rightBottomLabel.setText(QtGui.QApplication.translate("smartsyncdlg", "", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.mainTab), QtGui.QApplication.translate("smartsyncdlg", "&Main", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsGroupBox.setTitle(QtGui.QApplication.translate("smartsyncdlg", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.recursiveCheckBox.setText(QtGui.QApplication.translate("smartsyncdlg", "Be &recursive", None, QtGui.QApplication.UnicodeUTF8))
        self.backupCheckBox.setText(QtGui.QApplication.translate("smartsyncdlg", "&Backup destination file", None, QtGui.QApplication.UnicodeUTF8))
        self.hiddenCheckBox.setText(QtGui.QApplication.translate("smartsyncdlg", "I&gnore hidden items", None, QtGui.QApplication.UnicodeUTF8))
        self.contentCheckBox.setText(QtGui.QApplication.translate("smartsyncdlg", "Compar&e by content", None, QtGui.QApplication.UnicodeUTF8))
        self.ownershipCheckBox.setText(QtGui.QApplication.translate("smartsyncdlg", "Preserve o&wnerships", None, QtGui.QApplication.UnicodeUTF8))
        self.permissionsCheckBox.setText(QtGui.QApplication.translate("smartsyncdlg", "Preserve &permissions", None, QtGui.QApplication.UnicodeUTF8))
        self.timestampsCheckBox.setText(QtGui.QApplication.translate("smartsyncdlg", "Preserve &timestamps", None, QtGui.QApplication.UnicodeUTF8))
        self.unidirCheckBox.setText(QtGui.QApplication.translate("smartsyncdlg", "Be &unidirectional", None, QtGui.QApplication.UnicodeUTF8))
        self.l2rRadioButton.setText(QtGui.QApplication.translate("smartsyncdlg", "From left to right", None, QtGui.QApplication.UnicodeUTF8))
        self.r2lRadioButton.setText(QtGui.QApplication.translate("smartsyncdlg", "From right to left", None, QtGui.QApplication.UnicodeUTF8))
        self.excludeGroupBox.setTitle(QtGui.QApplication.translate("smartsyncdlg", "E&xclude the followings", None, QtGui.QApplication.UnicodeUTF8))
        self.excludeOpenButton.setText(QtGui.QApplication.translate("smartsyncdlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.addPushButton.setText(QtGui.QApplication.translate("smartsyncdlg", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.removePushButton.setText(QtGui.QApplication.translate("smartsyncdlg", "Remo&ve", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.optionsTab), QtGui.QApplication.translate("smartsyncdlg", "&Options", None, QtGui.QApplication.UnicodeUTF8))
        self.comparePushButton.setText(QtGui.QApplication.translate("smartsyncdlg", "&Compare", None, QtGui.QApplication.UnicodeUTF8))
        self.syncPushButton.setText(QtGui.QApplication.translate("smartsyncdlg", "&Synchronise", None, QtGui.QApplication.UnicodeUTF8))
        #self.profilesPushButton.setText(QtGui.QApplication.translate("smartsyncdlg", "Pro&files", None, QtGui.QApplication.UnicodeUTF8))
        #self.helpPushButton.setText(QtGui.QApplication.translate("smartsyncdlg", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.closePushButton.setText(QtGui.QApplication.translate("smartsyncdlg", "&Quit", None, QtGui.QApplication.UnicodeUTF8))

